
    <?php
      //this file is generated by the gvisions installer. do not edit this file, if you don't know, what you do!!
      $host = 'localhost';
      $user = 'root';
      $pass = '';
      $db   = 'gframework';
      define ('pfw','gframework_');
      define ('db','gframework');
      define ('datenbank','gframework');
    ?>
  