<?php
  
  foreach($_REQUEST as $k=>$v)
  {
	${$k} = $v;
  }
  
  $config =
  "
    <?php
      //this file is generated by the gvisions installer. do not edit this file, if you don't know, what you do!!
      \$host = '$host';
      \$user = '$user';
      \$pass = '$pass';
      \$db   = '$db';
      define ('pfw','$prafix');
      define ('db','$db');
      define ('datenbank','$db');
    ?>
  ";
  
  $file = fopen("../core/config/mysql.php", "w");
  if ($file == false) die("ERROR#Open File false");
  fwrite($file,$config);
  fclose($file);
  
  require_once("../core/config/mysql.php");
  
  mysql_connect($host, $user, $pass);
  mysql_select_db($db);
  
  $sql_query = file_get_contents("database_fw_ml_nw.sql");
  $sql = explode(";",$sql_query);
  $c = 0;
  foreach($sql as $line)
	{
    if (!empty($line) AND  $c < count($sql)-1)
    {
      $line = preg_replace("%PFW%", pfw,$line);
      mysql_query($line) or die ("ERROR#". htmlspecialchars($line). " <br><br> ".htmlspecialchars(mysql_error()));
    }
	$c++;
  }
?>